services:
  db:
    image: postgres:latest
    container_name: postgres-container-FA
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - finance-network

  script-runner:
    build: .
    container_name: finance-scraper
    depends_on:
      - db
    restart: "no"
    networks:
      - finance-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: ${POSTGRES_HOST}
    volumes:
      - .:/app
      - .env:/app/.env

volumes:
  pgdata:

networks:
  finance-network:
