services:
  db:
    image: postgres:latest
    container_name: postgres-container-FA
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - finance-network

  script-runner:
    build: .
    container_name: finance-scraper
    depends_on:
      - db
    restart: "no"
    networks:
      - finance-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financedb
      DB_HOST: db 
    volumes:
      - .:/app
      
volumes:
  pgdata:

networks:
  finance-network: