services:
  db:
    image: postgres:latest
    container_name: postgres-container-FA
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - finance-network

volumes:
  pgdata:

networks:
  finance-network: